AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  taxi-trips

  Taxi trips data in NYC

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.9
    Handler: main.handler

Resources:
  RawTaxiDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: raw-taxi-data
  TransformedTaxiDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: transformed-taxi-data
  RedshiftStagingDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: redshift-staging-data
  TaxiDataMinerFn:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      Timeout: 60
      CodeUri: lambdas/taxi_data_into_s3/
      Policies:
        - S3WritePolicy:
            BucketName: !Ref RawTaxiDataBucket
        - S3ReadPolicy:
            BucketName: !Ref RawTaxiDataBucket
      Environment:
        Variables:
          RAW_TAXI_DATA_BUCKET_NAME: !Ref RawTaxiDataBucket
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(30 days)
  GlueTaxiDataCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueCrawlerAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt RawTaxiDataBucket.Arn
                  - !Join
                    - '/'
                    - - !GetAtt RawTaxiDataBucket.Arn
                      - '*'
                  - !GetAtt TransformedTaxiDataBucket.Arn
                  - !Join
                    - '/'
                    - - !GetAtt TransformedTaxiDataBucket.Arn
                      - '*'
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*:/aws-glue/*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*:/custom-logs/*"
              - Effect: Allow
                Action:
                  - glue:*
                Resource: !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:crawler/glue-taxi-data-crawler"
              - Effect: Allow
                Action:
                  - glue:GetDatabase*
                  - glue:GetTable*
                  - glue:CreateTable
                  - glue:CreatePartition*
                  - glue:DeleteDatabase
                  - glue:DeletePartition*
                  - glue:Batch*
                Resource: 
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/taxitripsdb"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/taxitripsdb/*"
  GlueTaxiDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: 'taxitripsdb'
        Description: 'Glue DB for Taxi Trips Metadata'
  GlueTaxiDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: glue-taxi-data-crawler
      Role: !GetAtt GlueTaxiDataCrawlerRole.Arn
      DatabaseName: !Ref GlueTaxiDatabase
      Targets:
        S3Targets:
          - Path: !Ref RawTaxiDataBucket
            Exclusions:
              - '*.txt'
              - '*.csv'
          - Path: !Ref TransformedTaxiDataBucket
  RedshiftAccessDataRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: redshift.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3TransformedDataAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt TransformedTaxiDataBucket.Arn
                  - !Join
                    - '/'
                    - - !GetAtt TransformedTaxiDataBucket.Arn
                      - '*'
  GlueProcessRawDataJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AssetsFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource: 
                  - !GetAtt GlueAssetsBucket.Arn
                  - !Join
                    - '/'
                    - - !GetAtt GlueAssetsBucket.Arn
                      - '*'
        - PolicyName: S3ReadRawData
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource:
                  - !GetAtt RawTaxiDataBucket.Arn
                  - !Join
                    - '/'
                    - - !GetAtt RawTaxiDataBucket.Arn
                      - '*'
        - PolicyName: S3WriteTransformData
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt TransformedTaxiDataBucket.Arn
                  - !Join
                    - '/'
                    - - !GetAtt TransformedTaxiDataBucket.Arn
                      - '*'
        - PolicyName: GlueDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:*
                Resource: 
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${GlueTaxiDatabase}'
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${GlueTaxiDatabase}/*'
  GlueAssetsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: glue-assets-taxi-data
  GlueJobProcessRawData:
    Type: AWS::Glue::Job
    Properties:
      WorkerType: G.1X
      NumberOfWorkers: 2
      Timeout: 20
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Sub 's3://${GlueAssetsBucket}/process_raw_taxi_data.py'
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Name: process_raw_taxi_data
      Role: !Ref GlueProcessRawDataJobRole
      GlueVersion: '3.0'

