AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  taxi-trips

  Taxi trips data in NYC

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.9
    Handler: main.handler

Resources:
  RawTaxiDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: raw-taxi-data
  TaxiDataMinerFn:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      Timeout: 60
      CodeUri: lambdas/taxi_data_into_s3/
      Policies:
        - S3WritePolicy:
            BucketName: !Ref RawTaxiDataBucket
        - S3ReadPolicy:
            BucketName: !Ref RawTaxiDataBucket
      Environment:
        Variables:
          RAW_TAXI_DATA_BUCKET_NAME: !Ref RawTaxiDataBucket
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(30 days)
  GlueRawTaxiDataCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueCrawlerS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  !Join
                    - ''
                    - - !GetAtt RawTaxiDataBucket.Arn
                      - '*'
        - PolicyName: GlueCrawlerLogPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: GlueCrawlerGlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:*
                Resource: '*'
  GlueTaxiDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: 'taxitripsdb'
        Description: 'Glue DB for Taxi Trips Metadata'
  GlueRawTaxiDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: glue-raw-taxi-data-crawler
      Role: !GetAtt GlueRawTaxiDataCrawlerRole.Arn
      DatabaseName: !Ref GlueTaxiDatabase
      Targets:
        S3Targets:
          - Path: !Ref RawTaxiDataBucket
            Exclusions:
              - '*.txt'
